---
name: Docker images build and push

#on:
#  push:
#    branches:
#      - 'develop'
#    paths:
#      - util/dockerfiles/**
on:
    workflow_dispatch:


jobs:

    obtain-targets:
        runs-on: ubuntu-latest
        outputs:
            targets: ${{ steps.generate.outputs.targets }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: List targets
              id: generate
              uses: docker/bake-action/subaction/list-targets@v4
              with:
                  target: default
                  workdir: util/dockerfiles

    docker-buildx-bake:
        runs-on: [self-hosted, linux, x64]
        needs:
            - obtain-targets

        strategy:
            fail-fast: false
            matrix:
                target: ${{ fromJSON(needs.obtain-targets.outputs.targets) }}

        permissions:
            packages: write
            contents: read

        steps:

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and Push
              uses: docker/build-push-action@v6
              with:
                  source: '{{defaultContext}}:util/dockerfiles'
                  targets: ${{ matrix.target }}
                  provenance: true
                  push: true
